protected/controllers/CustomerController.php
<?php

class CustomerController extends Controller
{
	public function actionIndex()
	{
		$models = Customer::model()->findAll();

		$this->render('index', array(
			'models' => $models,
		));
	}

	public function actionView($urlName)
	{
		$model = $this->loadModel($urlName);

		$this->render('view', array(
			'model' => $model,
		));
	}

	public function loadModel($urlName)
	{
		$model=Customer::model()->with('projects')->findByAttributes(array(
			'urlName' => $urlName,
		));

		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}
}

protected/controllers/ProjectController.php
<?php

class ProjectController extends Controller
{
	public $categories = array();

	public function init()
	{
		$this->categories = Category::model()->findAll(array(
			'index' => 'urlName',
		));
	}

	public function actionIndex($urlName = null)
	{
		$category = null;

		if ($urlName !== null)
		{
			if (isset($this->categories[$urlName]))
			{
				$category = $this->categories[$urlName];
			}
			else
				throw new CHttpException(404, Yii::t('project', 'Указанной категории не существует'));			
		}

		$models = Project::model()->byCategory($urlName)->findAll();

		$this->render('index', array(
			'models' => $models,
			'category' => $category,
			'categories' => $this->categories,
		));
	}

	public function actionView($urlName)
	{
		$model = Project::model()->findByAttributes(array(
			'urlName' => $urlName,
		));

		if ($model === null)
			throw new CHttpException(404);

		$this->render('view', array(
			'model' => $model,
			'categories' => $this->categories,
		));
	}

	// Uncomment the following methods and override them if needed
	/*
	public function filters()
	{
		// return the filter configuration for this controller, e.g.:
		return array(
			'inlineFilterName',
			array(
				'class'=>'path.to.FilterClass',
				'propertyName'=>'propertyValue',
			),
		);
	}

	public function actions()
	{
		// return external action classes, e.g.:
		return array(
			'action1'=>'path.to.ActionClass',
			'action2'=>array(
				'class'=>'path.to.AnotherActionClass',
				'propertyName'=>'propertyValue',
			),
		);
	}
	*/
}

protected/controllers/ServiceController.php
<?php

class ServiceController extends Controller
{
	public $services = array();

	public function init()
	{
		$this->services = Service::model()->with('projects')->findAll(array(
			'index' => 'urlName',
		));
	}

	public function actionView($urlName = null)
	{
		if ($urlName === null)
		{
			$model = Service::model()->find();
		}
		else
		{
			if (isset($this->services[$urlName]))
			{
				$model = $this->services[$urlName];
			}
		}

		if ($model === null)
			throw new CHttpException(404, Yii::t('service', 'Указанной услуги не существует'));
		
		$this->render('view', array(
			'model' => $model,
			'projects' => $model->projects,
		));
	}
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/mail.php
<html>
	<body>
		<?php echo $content; ?>
	</body>
</html>

protected/views/layouts/main.php
<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8" />
	<title>Design Group</title>

	<base href="<?= Yii::app()->getBaseUrl(true); ?>/" />

	<link rel="stylesheet" href="style.css" />

	<!-- <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script> -->
	<!-- 33 KB -->

	<link  href="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.5.1/fotorama.css" rel="stylesheet"> <!-- 3 KB -->
	<script src="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.5.1/fotorama.js"></script> <!-- 16 KB -->
</head>

<body>
	<div class="page-wrapper">
		<div class="b-header">
			<?php if (Yii::app()->controller->id == 'site' && Yii::app()->controller->action->id == 'index'): ?>
				<i class="s s--logo"></i>
			<?php else: ?>
				<a href="<?= Yii::app()->getBaseUrl(true); ?>"><i class="s s--logo"></i></a>
			<?php endif; ?>
			<div class="b-header--contacts">
				<span><?= Config::value('phone'); ?></span>
				<br />
				<a href="<?= Config::value('email'); ?>"><?= Config::value('email'); ?></a>
			</div>
		</div>

		<div class="b-nav">
			<div class="b-nav--inner">
				<?php $this->widget('MainMenu',array(
					'items'=>array(
						array('label'=>'Работы', 'url'=>array('project/index'), 'active' => Yii::app()->controller->id == 'project'),
						array('label'=>'Услуги', 'url'=>array('service/view')),
						array('label'=>'Клиенты', 'url'=>array('customer/index')),
						array('label'=>'О Design Group', 'url'=>array('site/about')),
						// array('label' => 'Админка', 'url' => array('admin/main/index'), 'visible' => !Yii::app()->user->isGuest),
						// array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
						// array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
					),
					'activeCssClass' => 'active_page',
					'htmlOptions' => array(
						'class' => 'b-navmenu',
					),
				)); ?>
				<!--<span class="b-language">
					<a class="active" href="#">ru</a>
					<span>|</span>
					<a href="#">en</a>
				</span>-->
			</div>
		</div>

		<?php echo $content; ?>

		<div class="page-buffer"></div>
	</div>
	
	<div class="b-footer">
		<div class="b-footer--inner">
			<i class="s s--logo_footer"></i>

			<span class="b-footer__date">© 2008—2014</span>
			<span class="b-footer__name">JM Design Group</span>

			<div class="b-header--contacts footer">
				<span><?= Config::value('phone'); ?></span>
				<br />
				<a href="<?= Config::value('email'); ?>"><?= Config::value('email'); ?></a>
			</div>
		</div>
	</div>

</body>

</html>